SQLALCHEMY_DATABASE_URI = "sqlite:///database.db"
ADMIN_USERNAME = "Mohy"
ADMIN_PASSWORD = "123456789Mohy"
SECRET_KEY = "asdfghjkl123456tgvyhbujn23lakhsfcvb"
PAYMENT_MERCHANT = "sandbox"
PAYMENT_CALLBACK = "https://mohadese.pythonanywhere.com/verify"
PAYMENT_FIRST_REQUEST_URL = "https://sandbox.shepa.com/api/v1/token"
PAYMENT_VERIFY_REQUEST_URL = "https://sandbox.shepa.com/api/v1/verify"